on:
  push:
    tags:
      - '*'
name: Publish
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@main
    - name: Publish Mod
      uses: shanemadden/factorio-mod-portal-publish@stable
      env:
        FACTORIO_PASSWORD: ${{ secrets.FACTORIO_PASSWORD }}
        FACTORIO_USER: ${{ secrets.FACTORIO_USER }}